apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-node
  template:
    metadata:
      labels:
        app: kube-node
    spec:
      containers:
      - name: kube-node
        image: rnrifai/kube-node:latest
        ports:
        - containerPort: 3000
